---
default_language_version:
  python: 'python3.9'
fail_fast: true
ci:
    skip: ["prospector", "mypy"]

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.1.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-ast"
      - id: "check-byte-order-marker"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "check-merge-conflict"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "name-tests-test"
      - id: "trailing-whitespace"

  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: "v3.0.1"
    hooks:
      - id: "reorder-python-imports"
        args:
          - "--py39-plus"

  - repo: "https://github.com/psf/black"
    rev: "22.1.0"
    hooks:
      - id: "black"

  - repo: "local"
    hooks:

      - id: "prospector"
        name: "prospector"
        entry: "make lint"
        language: "system"
        types: ["python"]

      - id: "mypy"
        name: "mypy"
        entry: "make mypy"
        language: "system"
        types: ["python"]
