name: test

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"

jobs:
  test:
    name: test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: "macos-latest"
            python: "3.9"
          - os: "macos-latest"
            python: "3.13"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@main
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements/*') }}
      - run: python --version
      - run: python -mpip --version
      - run: python -mpip install -r requirements/requirements-dev.txt
      - run: python -mpip install ./
      - run: pytest --version
      - run: python -mpip cache info
      - run: mypy searvey
      - run: make cov
      # We only run on a single matrix case in order to speed up CI runtime
      - run: make exec_notebooks
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.10' }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
